# Theme Settings
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Eren's Professional Portfolio"
title_separator: "-"
subtitle: "Data Analysis and Business Intelligence"
name: "Eren"
description: "Welcome to my professional portfolio. Here, I showcase my expertise in data analysis and business intelligence, featuring projects and insights from my career in financial analysis and my transition to business intelligence."
url: "https://eren.github.io"  # Replace with your actual GitHub username
baseurl: ""  # Typically empty unless you're hosting in a subdirectory
repository: "eren/eren-portfolio"  # Replace with your GitHub username and repo name
logo: "/assets/images/logo.png"  # Path to your logo image
masthead_title: "Eren's Portfolio"

# Social Sharing
twitter:
  username: "eren"  # Replace with your Twitter username if you have one
facebook:
  username: "eren"  # Replace with your Facebook username if you have one
og_image: "/assets/images/og_image.jpg"  # Path to an image for social sharing

# Site Author
author:
  name: "Eren"
  avatar: "/assets/images/bio-photo.jpg"  # Path to your avatar image
  bio: "Passionate about turning data into actionable insights, I am a financial analyst transitioning to a career in business intelligence, focusing on data visualization and analysis."
  location: "Toronto, Canada"
  email: "eren@email.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:eren@email.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/eren"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eren"

# Analytics
analytics:
  provider: "google"  # Enable if you have Google Analytics
  google:
    tracking_id: "UA-XXXXX-Y"  # Replace with your tracking ID

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "erensportfolio"  # Replace with your Disqus shortname

# SEO Related
google_site_verification: "your_verification_token"
bing_site_verification: "your_verification_token"

# Additional features and plugins
search: true
search_provider: "lunr"

# Include and Exclude specific files
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"

# Markdown and Output settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: "America/Toronto"  # Set to your timezone

# Pagination settings (if using jekyll-paginate)
paginate: 5
paginate_path: "/page:num/"
